# Generated by Django 5.1.2 on 2024-10-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nhập tên sản phẩm', max_length=200)),
                ('price', models.FloatField(help_text='Nhập giá sản phẩm')),
                ('description', models.TextField(help_text='Nhập mô tả sản phẩm')),
                ('code', models.CharField(blank=True, help_text='Mã sản phẩm', max_length=8, null=True)),
            ],
        ),
    ]
