# Generated by Django 5.1.2 on 2024-10-28 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webBH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.ForeignKey(blank=True, help_text='Giỏ hàng', null=True, on_delete=django.db.models.deletion.CASCADE, to='webBH.cart'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Số lượng sản phẩm')),
                ('total', models.FloatField(help_text='Tổng tiền')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webBH.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='webBH.cartitem'),
        ),
    ]
