# Generated by Django 5.1.2 on 2024-10-28 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webBH', '0002_cart_product_cart_cartitem_cart_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(help_text='Nhập tên hãng', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Nhập tên loại sản phẩm', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, help_text='Mã sản phẩm', max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(help_text='Chọn hãng sản xuất', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webBH.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Chọn loại sản phẩm', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webBH.categories'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
